name: Build
on:
  push:
    branches:
    - master
    - "2.12-jakarta"
  pull_request:
    branches:
    - master
    - "2.12-jakarta"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: ['11']
        os: ['ubuntu-20.04']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: joschi/setup-jdk@v2.3.0
      with:
        java-version: ${{ matrix.java_version }}
    - uses: actions/cache@v2.1.3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build
      run: ./mvnw -V -B -ff -ntp -s .github/settings.xml verify
    - name: Deploy snapshot
      if: github.event_name != 'pull_request'
      env:
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
      run: ./mvnw -V -B -ff -ntp -s .github/settings.xml source:jar deploy
